config:
  debugEnabled: true
  adminEnabled: true
  metricsEnabled: true
  preInit: true
  multiparty: false

  organizationName: "exampleOrg"
  organizationKey: "0x75a99473917701038e854ef6999c76cd947c9f9e"
  # fireflyContractAddress: "0xeb7284ce905e0665b7d42cabe31c76c45da1d254"

  ethconnectUrl: "http://firefly-evmconnect:5000"

  postgresUrl: "postgres://postgres:firef1y@postgresql.default.svc:5432?sslmode=disable"
  postgresAutomigrate: true

  ipfsApiUrl: "http://ipfs.firefly-os:5001"
  ipfsGatewayUrl: "http://ipfs.firefly-os:8080"

core:
  metrics:
    serviceMonitor:
      enabled: true

dataexchange:
  certificate:
    enabled: true
    issuerRef:
      kind: ClusterIssuer
      name: selfsigned-ca

  tlsSecret:
    enabled: false

signer:
  enabled: true

evmconnect:
  enabled: true
  image:
    tag: v1.2.7
  config:
    jsonRpcUrl: "http://firefly-signer:8545"
