apiVersion: v1
version: 0.1.0
appVersion: 24.3.0
name: besu-node
description: Besu nodes for a POA network
keywords:
  - ethereum
  - besu
  - hyperledger
  - enterprise
  - blockchain
  - pegasys
  - consensys
home: https://besu.hyperledger.org
sources:
  - https://github.com/hyperledger/besu
maintainers:
  - name: Joshua Fernandes
    email: joshua.fernandes@consensys.net
icon: http://besu.hyperledger.org/en/latest/favicon.ico
